
#pragma once

#ifndef PHATSDK_USE_SMART_BOX
#define PHATSDK_USE_SMART_BOX 1
#endif

#ifndef PHATSDK_USE_WEENIE_STUB
#define PHATSDK_USE_WEENIE_STUB 1
#endif

#ifndef PHATSDK_IS_SERVER
#define PHATSDK_IS_SERVER 0
#endif

#ifndef PHATSDK_DISABLE_ANNOYING_WARNINGS
#define PHATSDK_DISABLE_ANNOYING_WARNINGS 1
#endif

#ifndef PHATSDK_RENDER_AVAILABLE
#define PHATSDK_RENDER_AVAILABLE 0
#endif

#ifndef PHATSDK_USE_PHYSICS_AND_WEENIE_DESC
#define PHATSDK_USE_PHYSICS_AND_WEENIE_DESC 1
#endif

#ifndef PHATSDK_USE_EXTENDED_CELL_DATA
#define PHATSDK_USE_EXTENDED_CELL_DATA 0
#endif

#ifndef PHATSDK_LOAD_SURFACES
#define PHATSDK_LOAD_SURFACES 1
#endif

#ifndef PHATSDK_INCLUDE_PHATDATABIN
#define PHATSDK_INCLUDE_PHATDATABIN 0
#endif

