
#pragma once

#include "Packable.h"

class CWeenieDefaults : public PackObj
{
public:
	CWeenieDefaults();
	virtual ~CWeenieDefaults();

	DECLARE_PACKABLE()

	DWORD m_FileVersion = 0;
	DWORD m_WCID = 0;
	std::string m_Description;
	DWORD m_Timestamp = 0;
	CACQualities m_Qualities;
	ObjDesc m_WorldObjDesc;
	bool m_bIsAutoGenerated = false;

	bool m_bHasValidArmorData = false;
	std::string m_sourceFile;

	ObjDesc m_WornObjDesc; // not saved
};

